version: "3.1"

services:
  application:
    image: application
    build:
      context: ./application
      dockerfile: Dockerfile
    depends_on:
      - redis
      - worker

  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  flower:
    image: mher/flower:0.9.7
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
    ports:
      - 8889:8888
    depends_on:
      - redis
